import * as T from '../../vendor/three.module.js';
import {arena,mallet} from './Arena.js';
import {character,animateCharacter} from '../characters/Characters.js';
import {ARENAS,legalSkill} from '../config/game.js';
function dispose(group){group.traverse(o=>{o.geometry?.dispose();if(o.material){for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose();}});}
export class Scene {
 constructor(host){this.host=host;this.scene=new T.Scene();this.scene.background=new T.Color(0x0b171d);this.scene.fog=new T.Fog(0x0b171d,35,65);this.camera=new T.PerspectiveCamera(40,1,.1,100);this.renderer=new T.WebGLRenderer({antialias:true,alpha:false});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.4;host.append(this.renderer.domElement);this.scene.add(new T.HemisphereLight(0xd7fff8,0x47405a,2.8));let key=new T.DirectionalLight(0xfff3df,4);key.position.set(-7,16,8);key.castShadow=true;key.shadow.mapSize.set(1024,1024);Object.assign(key.shadow.camera,{left:-12,right:12,top:14,bottom:-14});key.shadow.bias=-.001;this.scene.add(key);let fill=new T.PointLight(0x69dcc4,80,30);fill.position.set(7,5,-5);this.scene.add(fill);
 let floor=new T.Mesh(new T.PlaneGeometry(150,150),new T.MeshStandardMaterial({color:0x0c2026,roughness:.9}));floor.rotation.x=-Math.PI/2;floor.position.y=-1.7;floor.receiveShadow=true;this.scene.add(floor);
 this.players=[mallet(0x7ce0cc),mallet(0xf39caf)];this.players.forEach(m=>this.scene.add(m));this.puck=new T.Mesh(new T.CylinderGeometry(.27,.27,.15,32),new T.MeshStandardMaterial({color:0xffedb9,emissive:0xfbcf6b,emissiveIntensity:1.5,metalness:.6,roughness:.15}));this.puck.castShadow=true;this.scene.add(this.puck);this.trails=Array.from({length:18},()=>{let m=new T.Mesh(new T.SphereGeometry(.17,8,6),new T.MeshBasicMaterial({color:0xffe1a3,transparent:true,opacity:0}));this.scene.add(m);return m;});
 this.effects=[];this.skillMeshes=[null,null];this.ray=new T.Raycaster();this.plane=new T.Plane(new T.Vector3(0,1,0),-.55);this.side=1;this.mode='menu';this.configure('classic',['bear','cat']);new ResizeObserver(()=>this.resize()).observe(host);this.resize();}
 configure(type,chars){if(this.rink){this.scene.remove(this.rink.group);dispose(this.rink.group);}this.rink=arena(type);this.scene.add(this.rink.group);this.type=type;for(const c of this.cheers||[]){this.scene.remove(c);dispose(c);}this.cheers=chars.map((t,i)=>{let g=character(t);g.scale.setScalar(.8);g.position.set(i===0?6.1:-6.1,.4,i===0?5:-5);g.userData.baseY=.4;g.rotation.y=i===0?-.45:Math.PI-.45;this.scene.add(g);return g;});this.characters=chars;this.clearSkills();}
 clearSkills(){for(let i=0;i<2;i++)if(this.skillMeshes[i]){this.scene.remove(this.skillMeshes[i]);dispose(this.skillMeshes[i]);this.skillMeshes[i]=null;}}
 resize(){let w=this.host.clientWidth,h=this.host.clientHeight;if(!w||!h)return;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;const mobile=w/h<.7;const distance=mobile?38:26;this.camera.position.set(this.mode==='menu'?4:0,distance*.79,this.side*distance*.73);this.camera.lookAt(0,0,0);this.camera.updateProjectionMatrix();}
 setMode(mode,side=1){this.mode=mode;this.side=side;this.resize();}
 point(e){let b=this.renderer.domElement.getBoundingClientRect();this.ray.setFromCamera(new T.Vector2((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1),this.camera);let p=new T.Vector3();return this.ray.ray.intersectPlane(this.plane,p)?p:null;}
 placement(armed,point){if(this.zone){this.scene.remove(this.zone);dispose(this.zone);this.zone=null;}if(!armed)return;this.zone=new T.Group();this.scene.add(this.zone);const ring=(r,x,z,color,opacity)=>{let m=new T.Mesh(new T.RingGeometry(r-.045,r,64),new T.MeshBasicMaterial({color,transparent:true,opacity,side:T.DoubleSide}));m.rotation.x=-Math.PI/2;m.position.set(x,.48,z);this.zone.add(m);};ring(2.7,0,this.side*8,0xff607b,.9);for(let x=-3;x<=3;x+=1.5)for(let z=1.5;z<=5;z+=1.5)ring(.08,x,z*this.side,0x9bffd9,.6);if(point)ring(1.9,point.x,point.z,legalSkill(point.x,point.z,this.side)?0x93ffd4:0xff6379,.9);}
 burst(x,z,color){for(let i=0;i<30;i++){let m=new T.Mesh(new T.BoxGeometry(.08,.08,.08),new T.MeshBasicMaterial({color}));m.position.set(x,.7,z);this.scene.add(m);this.effects.push({m,v:new T.Vector3((Math.random()-.5)*9,Math.random()*6+1,(Math.random()-.5)*9),life:.7});}}
 render(state,dt,time){let lerp=this.remote?1-Math.exp(-dt*24):1;this.puck.position.lerp(new T.Vector3(state.puck.x,.57,state.puck.z),lerp);state.players.forEach((p,i)=>this.players[i].position.lerp(new T.Vector3(p.x,.55,p.z),lerp));this.trails.forEach((m,i)=>{if(i===0)m.position.copy(this.puck.position);else m.position.lerp(this.trails[i-1].position,Math.min(1,dt*40));m.material.opacity=(1-i/18)*.2*(state.phase==='playing'?1:0);m.scale.setScalar(1-i/22);});
 this.cheers.forEach((g,i)=>animateCharacter(g,time,state.phase==='goal'&&state.lastScorer===i?1:0,state.puck.x));
 state.skills.forEach((s,i)=>{let g=this.skillMeshes[i];if(!s){if(g){this.scene.remove(g);dispose(g);this.skillMeshes[i]=null;}return;}if(!g){g=character(s.type);g.scale.setScalar(.65);this.scene.add(g);this.skillMeshes[i]=g;let r=new T.Mesh(new T.RingGeometry(1.94,2,64),new T.MeshBasicMaterial({color:s.type==='duck'?0xffdd81:0xc2ffe5,transparent:true,opacity:.45,side:T.DoubleSide}));r.rotation.x=-Math.PI/2;r.position.y=-.05;g.add(r);g.userData.ring=r;}g.position.set(s.x,.5,s.z);g.rotation.y=i===0?0:Math.PI;let p=g.userData.parts;if(s.type==='bear'){let length=.55+(.5+.5*Math.sin(s.age*8));g.rotation.y=-Math.sin(s.age*2.7)*1.1;p.body.scale.x=length/.65;p.belly.scale.x=length/.65*.7;p.head.position.x=length/.65-.4;p['arm1'].position.x=length/.65;p['arm-1'].position.x=-length/.65;p['foot1'].position.x=length/.65*.5;p['foot-1'].position.x=-length/.65*.5;}if(s.type==='duck'){p.head.rotation.z=Math.sin(s.age*9)*.08;g.userData.ring.scale.setScalar(1+.08*Math.sin(s.age*12));}if(s.type==='cat'){g.position.x=Math.sin(s.age*4)*3.7;g.position.z=s.side*4.65;g.position.y=.5+Math.abs(Math.sin(s.age*8))*.5;g.userData.ring.visible=false;}});
 if(this.type==='wind'){let k=Math.floor(state.t/6)%3;this.rink.wind.children.forEach((m,i)=>{m.position.z+=(k===0?-1:k===1?1:0)*dt*4;m.position.x+=(k===2?Math.sin(state.t*1.4)*dt*4:0);if(m.position.z>8)m.position.z=-8;if(m.position.z<-8)m.position.z=8;if(m.position.x>5)m.position.x=-5;if(m.position.x<-5)m.position.x=5;});}
 for(let j=this.effects.length-1;j>=0;j--){let e=this.effects[j];e.life-=dt;e.m.position.addScaledVector(e.v,dt);e.v.y-=12*dt;if(e.life<0){this.scene.remove(e.m);dispose(e.m);this.effects.splice(j,1);}}
 this.renderer.render(this.scene,this.camera);}
}
