import test from 'node:test';import assert from 'node:assert/strict';import {Physics} from '../src/game/Physics.js';import {STEP,legalSkill,MALLET_RADIUS} from '../src/config/game.js';
function play(config={}){let g=new Physics({ai:false,...config});g.phase='playing';return g;}
function run(g,seconds){for(let t=0;t<seconds;t+=STEP)g.step(STEP);}
test('countdown and finite input / half bounds',()=>{let g=new Physics({ai:false});g.input(0,100,-100);assert.equal(g.players[0].tx,4.35-(MALLET_RADIUS-.62));assert.equal(g.players[0].tz,.72);g.input(0,NaN,5);assert.equal(g.players[0].tx,4.35-(MALLET_RADIUS-.62));run(g,3.1);assert.equal(g.phase,'playing');});
test('whole puck crossing scores exactly once and produces a winner',()=>{let g=play({target:3});g.scores[0]=2;Object.assign(g.puck,{x:0,z:-8.2,vz:-20});run(g,.1);assert.deepEqual(g.scores,[3,0]);assert.equal(g.phase,'over');assert.equal(g.winner,0);run(g,5);assert.equal(g.scores[0],3);});
test('wall and goalpost reject out-of-mouth shots',()=>{let g=play();Object.assign(g.puck,{x:2.2,z:-7.5,vz:-20});run(g,.05);assert.equal(g.scores[0],0);assert.ok(g.puck.vz>0);let h=play();Object.assign(h.puck,{x:1.65,z:-7.5,vz:-20});run(h,.05);assert.equal(h.scores[0],0);assert.ok(h.puck.z>-8);});
test('maximum speed puck does not tunnel through mallet',()=>{let g=play();Object.assign(g.players[0],{x:0,z:3,tx:0,tz:3});Object.assign(g.puck,{x:0,z:1,vz:28});run(g,.1);assert.ok(g.puck.vz<0);});
test('moving mallet transfers velocity',()=>{let g=play();Object.assign(g.puck,{x:0,z:3,vx:0,vz:0});Object.assign(g.players[0],{x:0,z:4.2,tx:0,tz:1});run(g,.12);assert.ok(g.puck.vz<-5);});
test('skill legality, cooldown and exact five second expiry',()=>{let g=play();assert.equal(g.activate(0,0,7),false);assert.equal(g.activate(0,0,3),true);assert.equal(g.activate(0,1,3),false);run(g,4.9);assert.ok(g.skills[0]);run(g,.11);assert.equal(g.skills[0],null);assert.ok(g.cooldowns[0]>8);assert.equal(legalSkill(0,7.1,1),false);});
test('bear body stays bounded and reflects puck',()=>{let g=play();g.activate(0,0,3);Object.assign(g.puck,{x:0,z:2.5,vz:8});run(g,.06);assert.ok(g.puck.vz<0);for(const b of g.skillBodies(g.skills[0]))assert.ok(Math.hypot(b.x,b.z-3)<2);});
test('duck captures, holds and releases on player hit',()=>{let g=play({characters:['duck','cat']});g.activate(0,0,3);Object.assign(g.puck,{x:.1,z:3,vx:1,vz:0});run(g,.1);assert.equal(g.puck.held,0);run(g,.3);assert.ok(Math.abs(g.puck.x)<.001);Object.assign(g.players[0],{x:0,z:4.5,tx:0,tz:1});run(g,.15);assert.equal(g.puck.held,-1);assert.ok(g.puck.vz<-1);});
test('cat patrol stays in rear half outside exclusion zone',()=>{let g=play({characters:['cat','cat']});g.activate(0,1,3);for(let t=0;t<5;t+=.02){let s={...g.skills[0],age:t};let b=g.skillBodies(s)[0];assert.equal(b.z,4.65);assert.ok(Math.abs(b.x)<=3.7);assert.ok(Math.hypot(b.x,b.z-8)>2.7);}});
test('desert sand slows puck more than classic',()=>{let a=play({arena:'classic'}),b=play({arena:'desert'});for(const g of [a,b])Object.assign(g.puck,{x:-2.4,z:2,vx:2,vz:0});run(a,.25);run(b,.25);assert.ok(b.puck.vx<a.puck.vx*.7);});
test('wind applies directional force and ice has less drag',()=>{let a=play({arena:'classic'}),b=play({arena:'ice'}),c=play({arena:'wind'});for(const g of [a,b,c])Object.assign(g.puck,{x:0,z:0,vx:3,vz:0});run(a,.3);run(b,.3);run(c,.3);assert.ok(b.puck.vx>a.puck.vx);assert.ok(c.puck.vz<0);});
test('snapshot round trip preserves authoritative state',()=>{let g=play();g.activate(0,1,3);run(g,.3);let h=new Physics();h.apply(JSON.parse(JSON.stringify(g.snapshot())));assert.deepEqual(h.snapshot(),g.snapshot());});
