import test from 'node:test';import assert from 'node:assert/strict';import {EventEmitter} from 'node:events';import {RoomService} from '../src/multiplayer/RoomService.js';
// Protocol-only transport: deliberately does not claim to exercise Internet/WebRTC.
class Channel extends EventEmitter{constructor(){super();this.open=false;this.bufferSize=0;}send(data){queueMicrotask(()=>this.other.emit('data',structuredClone(data)));}close(){if(!this.open)return;this.open=false;this.other.open=false;queueMicrotask(()=>{this.emit('close');this.other.emit('close');});}}
class MemoryPeer extends EventEmitter{static peers=new Map();constructor(id){super();this.id=id||crypto.randomUUID();this.links=[];queueMicrotask(()=>{if(MemoryPeer.peers.has(this.id)){this.emit('error',{type:'unavailable-id'});return;}MemoryPeer.peers.set(this.id,this);this.emit('open');});}connect(id){let a=new Channel(),b=new Channel();a.other=b;b.other=a;this.links.push(a);queueMicrotask(()=>{let remote=MemoryPeer.peers.get(id);if(!remote){this.emit('error',{type:'peer-unavailable'});return;}remote.links.push(b);remote.emit('connection',b);a.open=b.open=true;a.emit('open');b.emit('open');});return a;}disconnect(){if(MemoryPeer.peers.get(this.id)===this)MemoryPeer.peers.delete(this.id);this.emit('disconnected');}destroy(){for(let c of this.links)c.close();if(MemoryPeer.peers.get(this.id)===this)MemoryPeer.peers.delete(this.id);}}
globalThis.window={Peer:MemoryPeer};
const wait=(room,type,predicate=()=>true)=>new Promise((resolve,reject)=>{const f=e=>{if(predicate(e.detail)){clearTimeout(timer);room.removeEventListener(type,f);resolve(e.detail);}};const timer=setTimeout(()=>{room.removeEventListener(type,f);reject(new Error('Timed out: '+type));},1000);room.addEventListener(type,f);});
const cfg={arena:'classic',target:5,skills:true};
test('password room, both ready, authoritative input/state, rematch and disconnect',async()=>{let a=new RoomService(),b=new RoomService();try{await a.create(cfg,'bear','secret');const ready=wait(b,'lobby',x=>x.connected);await b.join(a.code,'duck','secret');await ready;assert.deepEqual(a.config.characters,['bear','duck']);let startedA=wait(a,'start'),startedB=wait(b,'start');a.setReady();assert.equal(a.ready[1],false);b.setReady();await Promise.all([startedA,startedB]);let input=wait(a,'input');b.send({type:'input',x:2,z:-3});assert.deepEqual(await input,{x:2,z:-3});let state=wait(b,'state');a.send({type:'state',state:{scores:[2,1]}});assert.deepEqual(await state,{scores:[2,1]});let lobby=wait(a,'lobby');b.rematch();await lobby;assert.deepEqual(a.ready,[false,false]);let disconnect=wait(a,'disconnect');b.close();await disconnect;}finally{a.close();b.close();}});
test('wrong password rejected without admitting guest',async()=>{let a=new RoomService(),b=new RoomService();try{await a.create(cfg,'bear','secret');let error=wait(b,'error');await b.join(a.code,'cat','wrong');assert.match(await error,/密碼/);assert.equal(a.accepted,false);assert.equal(b.accepted,false);}finally{a.close();b.close();}});
test('random pairing releases discovery slot for another pair',async()=>{let rooms=Array.from({length:4},()=>new RoomService());try{for(let i=0;i<4;i+=2){await rooms[i].random(cfg,'cat');let paired=wait(rooms[i+1],'lobby',x=>x.connected);await rooms[i+1].random(cfg,'duck');await paired;assert.equal(rooms[i].accepted,true);assert.equal(rooms[i+1].accepted,true);}assert.equal(rooms[0].connection.open,true);assert.equal(rooms[2].connection.open,true);}finally{rooms.forEach(r=>r.close());}});
