import test from 'node:test';import assert from 'node:assert/strict';
import * as T from '../vendor/three.module.js';
import {roundCorner} from '../src/game/Bounds.js';import {playCamera} from '../src/game/Camera.js';import {Physics} from '../src/game/Physics.js';import {CORNER_RADIUS as R,STEP} from '../src/config/game.js';
test('all four corners reflect radial shots inward and remain in the curve',()=>{for(const sx of [-1,1])for(const sz of [-1,1])for(const a of [.03,.3,.785,1.25,1.54]){const nx=sx*Math.cos(a),nz=sz*Math.sin(a);let p={x:sx*(5-R)+nx*(R-.2),z:sz*(8-R)+nz*(R-.2),r:.27,vx:nx*22,vz:nz*22};assert.ok(roundCorner(p,true));assert.ok(p.vx*nx+p.vz*nz<0);assert.ok(Math.hypot(Math.abs(p.x)-(5-R),Math.abs(p.z)-(8-R))<=R-p.r);assert.ok(Math.abs(Math.hypot(p.vx,p.vz)-22)<1e-6);}});
test('near-zero corner puck receives an inward release',()=>{let p={x:4.8,z:7.8,r:.27,vx:0,vz:0};roundCorner(p,true);assert.ok(p.vx<0&&p.vz<0);assert.ok(Math.hypot(p.vx,p.vz)>=.59);});
test('maximum-speed diagonal shots escape all four corners',()=>{for(const sx of [-1,1])for(const sz of [-1,1]){const g=new Physics({ai:false,skills:false,arena:'ice'});g.phase='playing';Object.assign(g.puck,{x:sx*3.5,z:sz*6.5,vx:sx*19,vz:sz*19});for(let t=0;t<.6;t+=STEP)g.step(STEP);assert.ok(Math.abs(g.puck.x)<3.5||Math.abs(g.puck.z)<6.5);assert.deepEqual(g.scores,[0,0]);}});
test('mallet targets cannot enter the corner wall',()=>{const g=new Physics({ai:false});for(const i of [0,1])for(const sx of [-1,1]){g.input(i,sx*20,i===0?20:-20);let p=g.players[i];assert.ok(Math.hypot(Math.abs(p.tx)-(5-R),Math.abs(p.tz)-(8-R))<=R-p.r+.001);}});
test('adaptive cameras contain table and goals on portrait, landscape, desktop and both sides',()=>{for(const [w,h] of [[390,684],[360,580],[430,772],[1280,740],[544,378]])for(const side of [-1,1]){const c=playCamera(w,h,side);for(const x of [-5.5,5.5])for(const z of [-9.1,9.1])for(const y of [-.45,1]){let p=new T.Vector3(x,y,z).project(c);assert.ok(Math.abs(p.x)<1&&Math.abs(p.y)<1,`${w} ${h} clipped`);}const ray=new T.Raycaster();const target=new T.Vector3(2,.55,4*side),ndc=target.clone().project(c);ray.setFromCamera(new T.Vector2(ndc.x,ndc.y),c);let hit=new T.Vector3();ray.ray.intersectPlane(new T.Plane(new T.Vector3(0,1,0),-.55),hit);assert.ok(hit.distanceTo(target)<1e-6);}});
test('phone playable area is substantially larger than Alpha 0.3',()=>{let old=new T.PerspectiveCamera(40,390/778,.1,100);old.position.set(0,38*.79,38*.73);old.lookAt(0,0,0);old.updateMatrixWorld();let current=playCamera(390,684);const height=(camera,pixels)=>Math.abs(new T.Vector3(0,.55,8).project(camera).y-new T.Vector3(0,.55,-8).project(camera).y)*pixels/2;assert.ok(height(current,684)>height(old,778)*1.35);});
