import {Music,MUSIC_TRACKS} from './audio/Music.js?v=0.7.2';
import {renderLobby} from './ui/Lobby.js?v=0.7.2';
import * as T from '../vendor/three.module.js?v=0.7.2';
import {CHARACTERS,ARENAS,STEP,COOLDOWN,clamp} from './config/game.js?v=0.7.2';
import {character} from './characters/Characters.js?v=0.7.2';
import {Physics} from './game/Physics.js?v=0.7.2';
import {Scene} from './game/Scene.js?v=0.7.2';
import {RoomService} from './multiplayer/RoomService.js?v=0.7.2';
const $=s=>document.querySelector(s);let selected='bear',arena='classic',mode='ai',running=false,armed=false,dragging=false,room=null,playerIndex=0,paused=false,finished=false,lastGoal=0,lastImpactId=0,accumulator=0,last=performance.now(),sendClock=0,frameTime=0,sound=false,audio=null,disconnectShown=false;
const music=new Music({onChange:updateMusicButton,onError:()=>toast('音樂暫時無法播放，請再點一次音樂按鈕。')});
function updateMusicButton(){const b=$('#music');b.classList.toggle('is-muted',!music.enabled);b.setAttribute('aria-pressed',String(music.enabled));b.setAttribute('aria-label',music.enabled?'關閉背景音樂':'開啟背景音樂');b.title=MUSIC_TRACKS[music.arena]?(music.enabled?'背景音樂已開啟':'背景音樂已關閉'):'此場地尚未加入背景音樂';}
function mountAudio(){const controls=$('#audio-controls');if($('#dialog').open)$('#dialog').insertBefore(controls,$('#dialog-content'));else if(running)$('#hud').append(controls);else $('.header-right').insertBefore(controls,$('#help'));}
$('#music').onclick=()=>{music.setEnabled(!music.enabled);if(music.enabled&&!MUSIC_TRACKS[music.arena])toast('此場地尚未加入背景音樂。');};
addEventListener('pagehide',()=>music.setHidden(true));addEventListener('pageshow',()=>music.setHidden(document.hidden));document.addEventListener('visibilitychange',()=>music.setHidden(document.hidden));
const view=new Scene($('#scene'));let game=new Physics({});
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',3500);}
function beep(freq=440,duration=.07){if(!sound)return;try{audio??=new AudioContext();audio.resume();let o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.055,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}catch{}}
function impactSound(e){if(!sound||frameTime-(impactSound.last??-1)<.045)return;impactSound.last=frameTime;try{audio??=new AudioContext();audio.resume();const wall=e.type==='wall',heavy=!wall&&e.strength>.65,start=audio.currentTime,duration=wall?.065:heavy?.14:.075;
 const tone=(freq,end,volume,type)=>{const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,start);o.frequency.exponentialRampToValueAtTime(end,start+duration);g.gain.setValueAtTime(.001,start);g.gain.linearRampToValueAtTime(volume,start+.003);g.gain.exponentialRampToValueAtTime(.001,start+duration);o.connect(g).connect(audio.destination);o.onended=()=>{o.disconnect();g.disconnect();};o.start(start);o.stop(start+duration);};
 tone(wall?780:heavy?220:440,wall?390:heavy?75:260,.025+e.strength*.055,wall?'sine':'triangle');if(!wall){tone(1500,650,.012+e.strength*.014,'sine');}if(heavy){tone(125,48,.045,'sine');
 // Short filtered air layer; independent from the music channel.
 impactSound.noise??=(()=>{const b=audio.createBuffer(1,Math.ceil(audio.sampleRate*.12),audio.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;return b;})();
 const n=audio.createBufferSource(),filter=audio.createBiquadFilter(),g=audio.createGain();n.buffer=impactSound.noise;filter.type='bandpass';filter.Q.value=.7;filter.frequency.setValueAtTime(2200,start);filter.frequency.exponentialRampToValueAtTime(700,start+.12);g.gain.setValueAtTime(.001,start);g.gain.linearRampToValueAtTime(.035*e.strength,start+.018);g.gain.exponentialRampToValueAtTime(.001,start+.12);n.connect(filter).connect(g).connect(audio.destination);n.onended=()=>{n.disconnect();filter.disconnect();g.disconnect();};n.start(start);n.stop(start+.12);}}catch{}}
function portraits(){let r=new T.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});r.setSize(180,180);r.setPixelRatio(1);let s=new T.Scene(),c=new T.PerspectiveCamera(35,1,.1,20);c.position.set(2.1,2.1,4.4);c.lookAt(0,.9,0);s.add(new T.HemisphereLight(0xffffff,0x66576f,3));let l=new T.DirectionalLight(0xffffff,4);l.position.set(-3,5,5);s.add(l);let result={};for(let type of Object.keys(CHARACTERS)){let g=character(type);s.add(g);r.render(s,c);result[type]=r.domElement.toDataURL();s.remove(g);g.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});}r.dispose();return result;}
const pics=portraits();
$('#characters').innerHTML=Object.entries(CHARACTERS).map(([id,c])=>`<button class="char-card ${id===selected?'active':''}" data-char="${id}" aria-pressed="${id===selected}"><img class="portrait" src="${pics[id]}" alt="${c.name} 3D 角色"><span><b>${c.name}</b><small>${c.en}</small><p>${c.title} · ${c.role}</p></span><span class="check">✓</span></button>`).join('');
$('#arenas').innerHTML=Object.entries(ARENAS).map(([id,c],i)=>`<button class="arena-card ${id===arena?'active':''}" data-arena="${id}" aria-pressed="${id===arena}"><span class="arena-dot" style="--c:${c.color}">${['◈','✦','❄','◬','≋'][i]}</span><span>${c.name}<small>${c.en}</small></span></button>`).join('');
function preview(){music.setArena(arena);view.configure(arena,[selected,'cat']);game=new Physics({arena,characters:[selected,'cat']});game.players[0].x=-1;game.players[1].x=1;game.puck.x=.6;game.puck.z=-1;$('#arena-title').textContent=ARENAS[arena].name;$('#arena-en').textContent=ARENAS[arena].en+' ARENA';$('#arena-description').textContent=ARENAS[arena].desc;}
$('#characters').onclick=e=>{let b=e.target.closest('[data-char]');if(!b)return;selected=b.dataset.char;document.querySelectorAll('[data-char]').forEach(c=>{c.classList.toggle('active',c===b);c.setAttribute('aria-pressed',c===b);});preview();toast(CHARACTERS[selected].desc);};
$('#arenas').onclick=e=>{let b=e.target.closest('[data-arena]');if(!b||mode==='random')return;arena=b.dataset.arena;document.querySelectorAll('[data-arena]').forEach(c=>{c.classList.toggle('active',c===b);c.setAttribute('aria-pressed',c===b);});preview();};
for(const b of document.querySelectorAll('[data-mode]'))b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(c=>c.classList.toggle('active',c===b));$('#mode-description').textContent={ai:'磨練你的擊球角度，隨時來一場。',online:'分享四碼房號，和朋友展開即時對決。',random:'配對使用經典場・5 分制・技能開啟。'}[mode];$('#play').innerHTML=(mode==='ai'?'開始對戰':mode==='online'?'好友對戰':'尋找對手')+' <span>↗</span>';$('#difficulty-label').hidden=mode!=='ai';$('#online-note').hidden=mode==='ai';$('#target').disabled=$('#skills').disabled=mode==='random';document.querySelectorAll('[data-arena]').forEach(x=>x.disabled=mode==='random');};
function config(){return {arena,target:Number($('#target').value),skills:$('#skills').checked,difficulty:$('#difficulty').value,characters:[selected,['bear','duck','cat'].filter(c=>c!==selected)[Math.floor(Math.random()*2)]],ai:true};}
function dialog(html,closable=true){$('#dialog-content').innerHTML=html;$('.dialog-close').hidden=!closable;if(!$('#dialog').open)$('#dialog').showModal();mountAudio();}
function closeDialog(){if(room&&!running){room.close();room=null;}$('#dialog').close();}
$('.dialog-close').onclick=closeDialog;$('#dialog').addEventListener('cancel',e=>{e.preventDefault();if(!$('.dialog-close').hidden)closeDialog();});
$('#help').onclick=()=>{if(running&&!room){paused=true;}dialog(`<div class="eyebrow">HOW TO PLAY</div><h2>反彈，就是你的武器。</h2><p>在我方半場拖曳推盤。快速揮動會打出更強的擊球；善用兩側牆壁製造角度。</p><p>點右下角夥伴，再點綠色合法區域施放技能。每次持續 5 秒，冷卻 14 秒。紅色球門禁區無法放置。</p><p>🐻 皮皮熊：半徑內伸長身體反彈球。<br>🐤 吸吸鴨：吸住球，等你撞擊射出。<br>🐱 跳跳貓：後半場跳動，攔截來球。</p><p>桌機：拖曳或方向鍵 / WASD；空白鍵準備技能。<br>手機：手指滑動推盤，點角色施放。<br>先達到設定分數獲勝。</p><button id="help-done" class="primary">我準備好了</button>`);$('#help-done').onclick=()=>{$('#dialog').close();paused=false;};};
$('#dialog').addEventListener('close',()=>{mountAudio();if(running&&!finished)paused=false;});
$('#sound').onclick=()=>{sound=!sound;$('#sound').classList.toggle('is-muted',!sound);$('#sound').setAttribute('aria-pressed',String(sound));$('#sound').title=sound?'音效已開啟':'音效已關閉';$('#sound').setAttribute('aria-label',sound?'關閉音效':'開啟音效');beep();};
function start(c){music.setArena(c.arena);$('#dialog').close();running=true;finished=false;paused=false;disconnectShown=false;armed=false;lastGoal=0;lastImpactId=0;accumulator=0;playerIndex=room&&!room.host?1:0;game=new Physics(c);view.configure(c.arena,c.characters);view.remote=!!room&&!room.host;document.body.classList.add('playing');$('#menu').hidden=true;$('#hud').hidden=false;view.setMode('play',playerIndex===0?1:-1);mountAudio();$('#pause').hidden=!!room;$('#match-arena').textContent=ARENAS[c.arena].name;$('#match-rule').textContent=`先得 ${c.target} 分`;$('#player-label').textContent='你 · '+CHARACTERS[c.characters[playerIndex]].name;$('#opponent-label').textContent=(room?'對手 · ':'電腦 · ')+CHARACTERS[c.characters[1-playerIndex]].name;$('#skill-icon').innerHTML='<img alt="角色" src="'+pics[c.characters[playerIndex]]+'" style="width:45px;height:45px;object-fit:contain">';$('#skill-name').textContent=CHARACTERS[c.characters[playerIndex]].title;$('#network-label').textContent=room?'正在同步':'';view.placement(false);}
function home(){room?.close();room=null;running=false;paused=false;armed=false;dragging=false;$('#dialog').close();document.body.classList.remove('playing');$('#menu').hidden=false;$('#hud').hidden=true;view.setMode('menu');view.placement(false);preview();mountAudio();}
$('#leave').onclick=()=>{if(!room)paused=true;dialog('<h2>離開這場對戰？</h2><p>目前比分不會保留。</p><button id="leave-yes" class="primary">離開對戰</button><button id="leave-no" class="secondary">繼續比賽</button>');$('#leave-yes').onclick=home;$('#leave-no').onclick=()=>{$('#dialog').close();paused=false;};};
$('#pause').onclick=()=>{paused=!paused;$('#pause').textContent=paused?'▶':'Ⅱ';};
function bindRoom(){const active=room;room.addEventListener('lobby',e=>{if(room!==active)return;running=false;showLobby(e.detail);});room.addEventListener('start',e=>{if(room===active)start(e.detail);});room.addEventListener('input',e=>{if(running)game.input(1,e.detail.x,e.detail.z);});room.addEventListener('skill',e=>{if(running)game.activate(1,e.detail.x,e.detail.z);});room.addEventListener('state',e=>{if(running&&!room.host)game.apply(e.detail);});room.addEventListener('latency',e=>{$('#network-label').textContent=e.detail+' ms · 即時連線';});room.addEventListener('error',e=>{if(room!==active)return;connectionError(e.detail);});room.addEventListener('disconnect',()=>{if(room!==active||disconnectShown)return;disconnectShown=true;connectionError('對方已離線或網路中斷。這場對戰已停止。');});}
function connectionError(message){running=false;room?.close();room=null;dialog('<h2>連線暫時中斷</h2><p id="connection-message"></p><button id="error-back" class="primary">返回首頁</button>',false);$('#connection-message').textContent=String(message);$('#error-back').onclick=home;}
function showLobby(info){music.setArena(info.config.arena);armed=false;dragging=false;view.placement(false);dialog('',false);renderLobby($('#dialog-content'),info,{pics,onCharacter:id=>room?.setCharacter(id),onArena:id=>room?.setArena(id),onReady:()=>room?.setReady(),onLeave:home});}

async function network(action,code='',password=''){room?.close();room=new RoomService();const active=room;bindRoom();dialog('<h2>正在連接競技場…</h2><p>建立安全的點對點連線，請稍候。</p><button id="cancel-connect" class="secondary">取消</button>',false);$('#cancel-connect').onclick=home;try{if(action==='create')await active.create(config(),selected,password);if(action==='join')await active.join(code,selected,password);if(action==='random')await active.random(config(),selected);if(room!==active)active.close();}catch(e){if(room===active)connectionError(e.message||'連線失敗，請稍後再試。');}}
$('#play').onclick=()=>{beep(660);if(mode==='ai'){start(config());return;}if(mode==='random'){network('random');return;}dialog('<div class="eyebrow">PLAY TOGETHER</div><h2>邀請你的對手</h2><p>建立房間分享四碼房號，或輸入朋友的房號加入。</p><label>房間密碼（選填）<input id="password" type="password" maxlength="32" placeholder="留空即可免密碼加入" autocomplete="off"></label><button id="create-room" class="primary">建立房間</button><label>加入朋友的房間<input id="room-number" type="text" inputmode="numeric" maxlength="4" placeholder="4 碼房號" autocomplete="off"></label><button id="join-room" class="secondary">加入房間</button>');$('#create-room').onclick=()=>network('create','',$('#password').value);$('#join-room').onclick=()=>{let c=$('#room-number').value.trim();if(!/^\d{4}$/.test(c)){toast('請輸入 4 位數房號');return;}network('join',c,$('#password').value);};};
function arm(){if(!running||paused||game.phase!=='playing'||!game.config.skills||game.cooldowns[playerIndex]>0)return;armed=!armed;view.placement(armed);$('#hint').textContent=armed?'點綠色區域放置；紅色禁區不可放置':'拖曳我方推盤擊球';}
$('#skill').onclick=arm;
const canvas=view.renderer.domElement;
function move(p){if(room&&!room.host)room.send({type:'input',x:p.x,z:p.z});else game.input(playerIndex,p.x,p.z);}
canvas.addEventListener('pointerdown',e=>{if(!running||paused||game.phase!=='playing')return;let p=view.point(e);if(!p)return;if(armed){if(room&&!room.host){import('./config/game.js?v=0.7.2').then(({legalSkill})=>{if(!legalSkill(p.x,p.z,-1)){toast('請放在綠色合法區域，避開球門');return;}room.send({type:'skill',x:p.x,z:p.z});armed=false;view.placement(false);});}else if(game.activate(playerIndex,p.x,p.z)){armed=false;view.placement(false);beep(780);}else toast('請放在綠色合法區域，避開球門');return;}dragging=true;canvas.setPointerCapture(e.pointerId);move(p);});
canvas.addEventListener('pointermove',e=>{if(!running||paused)return;let p=view.point(e);if(!p)return;if(armed)view.placement(true,p);else if(dragging)move(p);});for(const name of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(name,()=>dragging=false);
const keys=new Set();addEventListener('keydown',e=>{if(!running||$('#dialog').open)return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','w','a','s','d'].includes(e.key)){e.preventDefault();keys.add(e.key);if(e.key===' '&&!e.repeat)arm();}});addEventListener('keyup',e=>keys.delete(e.key));addEventListener('blur',()=>{keys.clear();dragging=false;if(running&&!room)paused=true;});document.addEventListener('visibilitychange',()=>{if(document.hidden&&running&&!room)paused=true;});
function finish(){finished=true;room?.markFinished();let win=game.winner===playerIndex;beep(win?880:220,.4);dialog(`<div class="eyebrow">MATCH COMPLETE</div><h2>${win?'這一場，由你寫下。':'下一球，再扳回來。'}</h2><div class="room-code">${game.scores[playerIndex]} : ${game.scores[1-playerIndex]}</div><p style="text-align:center">${win?'漂亮的反彈！你贏得了這場對決。':'對手拿下了勝利，再試試不同夥伴與戰術。'}</p><button id="rematch" class="primary">${room?'回房間 · 選擇夥伴與競技場':'再來一局'}</button><button id="back-home" class="secondary">回首頁</button>`,false);$('#rematch').onclick=()=>{if(room)room.rematch();else start(game.config);};$('#back-home').onclick=home;}
function frame(now){const dt=Math.min((now-last)/1000,.05);last=now;frameTime+=dt;if(running&&!paused){if(keys.size&&game.phase==='playing'){let m=game.players[playerIndex],side=playerIndex===0?1:-1;move({x:m.tx+((keys.has('d')||keys.has('ArrowRight'))-(keys.has('a')||keys.has('ArrowLeft')))*dt*14*side,z:m.tz+((keys.has('s')||keys.has('ArrowDown'))-(keys.has('w')||keys.has('ArrowUp')))*dt*14*side});}if(!room||room.host){accumulator+=dt;while(accumulator>=STEP){game.step(STEP);accumulator-=STEP;}sendClock+=dt;if(room&&sendClock>1/30){room.send({type:'state',state:game.snapshot()});sendClock=0;}}if(game.goalId!==lastGoal){lastGoal=game.goalId;view.burst(0,game.lastScorer===0?-7:7,0xffde91);beep(660,.25);document.body.animate([{transform:'translate(0)'},{transform:'translate(3px, 2px)'},{transform:'translate(-3px, -1px)'},{transform:'translate(0)'}],{duration:180});}game.events.length=0;const impact=game.impact;if(impact?.id&&impact.id!==lastImpactId){lastImpactId=impact.id;if(game.t-impact.t<.2&&game.phase==='playing'){view.hitFeedback(impact);impactSound(impact);}}if(game.phase==='over'&&!finished)finish();}
 if(running){$('#player-score').textContent=game.scores[playerIndex];$('#opponent-score').textContent=game.scores[1-playerIndex];$('#announcement').textContent=paused?'暫停':game.phase==='countdown'?Math.max(1,Math.ceil(game.wait)):game.phase==='goal'?(game.lastScorer===playerIndex?'GOAL!':'對手得分'):'';let cool=game.cooldowns[playerIndex],skill=game.skills[playerIndex];$('#skill').disabled=!game.config.skills||cool>0||game.phase!=='playing'||paused;$('#skill-state').textContent=!game.config.skills?'本場技能關閉':skill?`技能發動中 · ${(5-skill.age).toFixed(1)} 秒`:cool>0?`充能中 · ${Math.ceil(cool)} 秒`:armed?'選擇場上位置':'技能就緒 · 點擊放置';$('#skill circle').style.strokeDashoffset=170*(cool/COOLDOWN);$('#wind-label').textContent=game.config.arena==='wind'?['↑ 北向氣流 · 下方順風','↓ 南向氣流 · 下方逆風','↔ 中央橫向氣流'][Math.floor(game.t/6)%3]:'';}
 view.render(game,dt,frameTime);requestAnimationFrame(frame);}
preview();$('#loading').remove();requestAnimationFrame(frame);
